modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/MeekTheSneak/Gathering/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}

Unofficial Fan Content permitted under the Fan Content Policy. Not approved/endorsed by
Wizards. Portions of the materials used are property of Wizards of the Coast.
(c)Wizards of the Coast LLC.

Card data and images courtesy of Scryfall. This mod ships no card images and redistributes
no card data; every client fetches and caches its own.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
